import type { Item } from "./types";

/**
 * Runtime assessment bank for the P2 adaptive session.
 *
 * Difficulty and discrimination values are uncalibrated demo seed values, not
 * official educational cut scores. Audio-led items deliberately point to local
 * public assets so the active assessment has no runtime TTS dependency.
 */
export const itemBank: Item[] = [
  // English — hear-word
  {
    id: "en-hw-01",
    format: "hear-word",
    language: "en",
    prompt: "cat",
    audioUrl: "/audio/en-hw-01.mp3",
    choices: [
      { id: "a", emoji: "🐱", label: "cat" },
      { id: "b", emoji: "🐶", label: "dog" },
      { id: "c", emoji: "🐟", label: "fish" },
      { id: "d", emoji: "🐦", label: "bird" },
    ],
    correctChoiceId: "a",
    difficulty: -2.4,
    discrimination: 1.2,
  },
  {
    id: "en-hw-02",
    format: "hear-word",
    language: "en",
    prompt: "book",
    audioUrl: "/audio/en-hw-02.mp3",
    choices: [
      { id: "a", emoji: "⚽", label: "ball" },
      { id: "b", emoji: "📖", label: "book" },
      { id: "c", emoji: "✏️", label: "pencil" },
      { id: "d", emoji: "🪑", label: "chair" },
    ],
    correctChoiceId: "b",
    difficulty: -1.5,
    discrimination: 1.2,
  },
  {
    id: "en-hw-03",
    format: "hear-word",
    language: "en",
    prompt: "chair",
    audioUrl: "/audio/en-hw-03.mp3",
    choices: [
      { id: "a", emoji: "🛏️", label: "bed" },
      { id: "b", emoji: "🪑", label: "chair" },
      { id: "c", emoji: "🚪", label: "door" },
      { id: "d", emoji: "🪟", label: "window" },
    ],
    correctChoiceId: "b",
    difficulty: -0.7,
    discrimination: 1.2,
  },
  {
    id: "en-hw-04",
    format: "hear-word",
    language: "en",
    prompt: "umbrella",
    audioUrl: "/audio/en-hw-04.mp3",
    choices: [
      { id: "a", emoji: "🧢", label: "cap" },
      { id: "b", emoji: "👟", label: "shoe" },
      { id: "c", emoji: "☂️", label: "umbrella" },
      { id: "d", emoji: "🧥", label: "coat" },
    ],
    correctChoiceId: "c",
    difficulty: 0.1,
    discrimination: 1.2,
  },
  {
    id: "en-hw-05",
    format: "hear-word",
    language: "en",
    prompt: "hungry",
    audioUrl: "/audio/en-hw-05.mp3",
    choices: [
      { id: "a", emoji: "😀", label: "happy" },
      { id: "b", emoji: "😴", label: "sleepy" },
      { id: "c", emoji: "😢", label: "sad" },
      { id: "d", emoji: "🤤", label: "hungry" },
    ],
    correctChoiceId: "d",
    difficulty: 0.9,
    discrimination: 1.2,
  },
  {
    id: "en-hw-06",
    format: "hear-word",
    language: "en",
    prompt: "under",
    audioUrl: "/audio/en-hw-06.mp3",
    choices: [
      { id: "a", emoji: "⚽⬇️🪑", label: "ball under a table" },
      { id: "b", emoji: "⚽🔝🪑", label: "ball on a table" },
      { id: "c", emoji: "⚽↔️🪑", label: "ball beside a table" },
      { id: "d", emoji: "⚽🏠", label: "ball in a house" },
    ],
    correctChoiceId: "a",
    difficulty: 1.8,
    discrimination: 1.2,
  },

  // Filipino — hear-word
  {
    id: "fil-hw-01",
    format: "hear-word",
    language: "fil",
    prompt: "pusa",
    audioUrl: "/audio/fil-hw-01.mp3",
    choices: [
      { id: "a", emoji: "🐶", label: "aso" },
      { id: "b", emoji: "🐱", label: "pusa" },
      { id: "c", emoji: "🐟", label: "isda" },
      { id: "d", emoji: "🐦", label: "ibon" },
    ],
    correctChoiceId: "b",
    difficulty: -2.3,
    discrimination: 1.2,
  },
  {
    id: "fil-hw-02",
    format: "hear-word",
    language: "fil",
    prompt: "aklat",
    audioUrl: "/audio/fil-hw-02.mp3",
    choices: [
      { id: "a", emoji: "✏️", label: "lapis" },
      { id: "b", emoji: "📖", label: "aklat" },
      { id: "c", emoji: "⚽", label: "bola" },
      { id: "d", emoji: "🪑", label: "upuan" },
    ],
    correctChoiceId: "b",
    difficulty: -1.4,
    discrimination: 1.2,
  },
  {
    id: "fil-hw-03",
    format: "hear-word",
    language: "fil",
    prompt: "upuan",
    audioUrl: "/audio/fil-hw-03.mp3",
    choices: [
      { id: "a", emoji: "🪑", label: "upuan" },
      { id: "b", emoji: "🛏️", label: "kama" },
      { id: "c", emoji: "🚪", label: "pinto" },
      { id: "d", emoji: "🪟", label: "bintana" },
    ],
    correctChoiceId: "a",
    difficulty: -0.6,
    discrimination: 1.2,
  },
  {
    id: "fil-hw-04",
    format: "hear-word",
    language: "fil",
    prompt: "payong",
    audioUrl: "/audio/fil-hw-04.mp3",
    choices: [
      { id: "a", emoji: "👟", label: "sapatos" },
      { id: "b", emoji: "☂️", label: "payong" },
      { id: "c", emoji: "🧢", label: "sumbrero" },
      { id: "d", emoji: "🧥", label: "dyaket" },
    ],
    correctChoiceId: "b",
    difficulty: 0.2,
    discrimination: 1.2,
  },
  {
    id: "fil-hw-05",
    format: "hear-word",
    language: "fil",
    prompt: "gutom",
    audioUrl: "/audio/fil-hw-05.mp3",
    choices: [
      { id: "a", emoji: "😴", label: "antok" },
      { id: "b", emoji: "😀", label: "masaya" },
      { id: "c", emoji: "🤤", label: "gutom" },
      { id: "d", emoji: "😢", label: "malungkot" },
    ],
    correctChoiceId: "c",
    difficulty: 1,
    discrimination: 1.2,
  },
  {
    id: "fil-hw-06",
    format: "hear-word",
    language: "fil",
    prompt: "ilalim",
    audioUrl: "/audio/fil-hw-06.mp3",
    choices: [
      { id: "a", emoji: "⚽🔝🪑", label: "bola sa ibabaw ng mesa" },
      { id: "b", emoji: "⚽↔️🪑", label: "bola sa tabi ng mesa" },
      { id: "c", emoji: "⚽🏠", label: "bola sa bahay" },
      { id: "d", emoji: "⚽⬇️🪑", label: "bola sa ilalim ng mesa" },
    ],
    correctChoiceId: "d",
    difficulty: 1.9,
    discrimination: 1.2,
  },

  // English — hear-sentence
  {
    id: "en-hs-01",
    format: "hear-sentence",
    language: "en",
    prompt: "The cat is sleeping on the bed.",
    audioUrl: "/audio/en-hs-01.mp3",
    choices: [
      { id: "a", emoji: "🐱💤🛏️", label: "cat sleeping on a bed" },
      { id: "b", emoji: "🐱🍌", label: "cat eating a banana" },
      { id: "c", emoji: "🐱🏃", label: "cat running" },
      { id: "d", emoji: "🐱📖", label: "cat reading" },
    ],
    correctChoiceId: "a",
    difficulty: -2,
    discrimination: 1.2,
  },
  {
    id: "en-hs-02",
    format: "hear-sentence",
    language: "en",
    prompt: "The child is eating an apple.",
    audioUrl: "/audio/en-hs-02.mp3",
    choices: [
      { id: "a", emoji: "🧒⚽", label: "child playing with a ball" },
      { id: "b", emoji: "🧒🍎", label: "child eating an apple" },
      { id: "c", emoji: "🧒📖", label: "child reading a book" },
      { id: "d", emoji: "🧒🛁", label: "child taking a bath" },
    ],
    correctChoiceId: "b",
    difficulty: -1.1,
    discrimination: 1.2,
  },
  {
    id: "en-hs-03",
    format: "hear-sentence",
    language: "en",
    prompt: "It is raining, so Maya holds an umbrella.",
    audioUrl: "/audio/en-hs-03.mp3",
    choices: [
      { id: "a", emoji: "🧒☂️🌧️", label: "child holding an umbrella in rain" },
      { id: "b", emoji: "🧒🕶️☀️", label: "child wearing sunglasses in sun" },
      { id: "c", emoji: "🧒🏊", label: "child swimming" },
      { id: "d", emoji: "🧒⛄", label: "child building a snowman" },
    ],
    correctChoiceId: "a",
    difficulty: -0.2,
    discrimination: 1.2,
  },
  {
    id: "en-hs-04",
    format: "hear-sentence",
    language: "en",
    prompt: "The ball is under the table.",
    audioUrl: "/audio/en-hs-04.mp3",
    choices: [
      { id: "a", emoji: "⚽🔝🪑", label: "ball on a table" },
      { id: "b", emoji: "⚽⬇️🪑", label: "ball under a table" },
      { id: "c", emoji: "⚽↔️🪑", label: "ball beside a table" },
      { id: "d", emoji: "⚽🏠", label: "ball in a house" },
    ],
    correctChoiceId: "b",
    difficulty: 0.6,
    discrimination: 1.2,
  },
  {
    id: "en-hs-05",
    format: "hear-sentence",
    language: "en",
    prompt: "Before school, Mia washes her hands.",
    audioUrl: "/audio/en-hs-05.mp3",
    choices: [
      { id: "a", emoji: "🧒🏫➡️🧼👐", label: "child washes hands after school" },
      { id: "b", emoji: "🧒🛏️➡️🏫", label: "child goes from bed to school" },
      { id: "c", emoji: "🧒🧼👐➡️🏫", label: "child washes hands before school" },
      { id: "d", emoji: "🧒🍌➡️🏫", label: "child eats a banana before school" },
    ],
    correctChoiceId: "c",
    difficulty: 1.4,
    discrimination: 1.2,
  },
  {
    id: "en-hs-06",
    format: "hear-sentence",
    language: "en",
    prompt: "The child puts the apple in the basket, not on the table.",
    audioUrl: "/audio/en-hs-06.mp3",
    choices: [
      { id: "a", emoji: "🍎🔝🪑", label: "apple on a table" },
      { id: "b", emoji: "🍎➡️🧺", label: "apple in a basket" },
      { id: "c", emoji: "🍎⬇️🪑", label: "apple under a table" },
      { id: "d", emoji: "🍎➡️🎒", label: "apple in a bag" },
    ],
    correctChoiceId: "b",
    difficulty: 2.3,
    discrimination: 1.2,
  },

  // Filipino — hear-sentence
  {
    id: "fil-hs-01",
    format: "hear-sentence",
    language: "fil",
    prompt: "Natutulog ang pusa sa kama.",
    audioUrl: "/audio/fil-hs-01.mp3",
    choices: [
      { id: "a", emoji: "🐱💤🛏️", label: "pusang natutulog sa kama" },
      { id: "b", emoji: "🐱🍌", label: "pusang kumakain ng saging" },
      { id: "c", emoji: "🐱🏃", label: "pusang tumatakbo" },
      { id: "d", emoji: "🐱📖", label: "pusang nagbabasa" },
    ],
    correctChoiceId: "a",
    difficulty: -2.1,
    discrimination: 1.2,
  },
  {
    id: "fil-hs-02",
    format: "hear-sentence",
    language: "fil",
    prompt: "Kumakain si Ana ng saging.",
    audioUrl: "/audio/fil-hs-02.mp3",
    choices: [
      { id: "a", emoji: "🧒🍌", label: "batang kumakain ng saging" },
      { id: "b", emoji: "🧒⚽", label: "batang naglalaro ng bola" },
      { id: "c", emoji: "🧒📖", label: "batang nagbabasa" },
      { id: "d", emoji: "🧒🛁", label: "batang naliligo" },
    ],
    correctChoiceId: "a",
    difficulty: -1,
    discrimination: 1.2,
  },
  {
    id: "fil-hs-03",
    format: "hear-sentence",
    language: "fil",
    prompt: "Umuulan kaya may payong si Ben.",
    audioUrl: "/audio/fil-hs-03.mp3",
    choices: [
      { id: "a", emoji: "🧒🕶️☀️", label: "batang naka-sunglasses sa araw" },
      { id: "b", emoji: "🧒☂️🌧️", label: "batang may payong sa ulan" },
      { id: "c", emoji: "🧒🏊", label: "batang lumalangoy" },
      { id: "d", emoji: "🧒⛄", label: "batang gumagawa ng snowman" },
    ],
    correctChoiceId: "b",
    difficulty: -0.1,
    discrimination: 1.2,
  },
  {
    id: "fil-hs-04",
    format: "hear-sentence",
    language: "fil",
    prompt: "Ang bola ay nasa ilalim ng mesa.",
    audioUrl: "/audio/fil-hs-04.mp3",
    choices: [
      { id: "a", emoji: "⚽⬇️🪑", label: "bola sa ilalim ng mesa" },
      { id: "b", emoji: "⚽🔝🪑", label: "bola sa ibabaw ng mesa" },
      { id: "c", emoji: "⚽↔️🪑", label: "bola sa tabi ng mesa" },
      { id: "d", emoji: "⚽🏠", label: "bola sa bahay" },
    ],
    correctChoiceId: "a",
    difficulty: 0.7,
    discrimination: 1.2,
  },
  {
    id: "fil-hs-05",
    format: "hear-sentence",
    language: "fil",
    prompt: "Bago pumasok sa paaralan, naghugas ng kamay si Mia.",
    audioUrl: "/audio/fil-hs-05.mp3",
    choices: [
      { id: "a", emoji: "🧒🏫➡️🧼👐", label: "naghugas pagkatapos ng paaralan" },
      { id: "b", emoji: "🧒🧼👐➡️🏫", label: "naghugas bago ang paaralan" },
      { id: "c", emoji: "🧒🛏️➡️🏫", label: "mula kama papuntang paaralan" },
      { id: "d", emoji: "🧒🍌➡️🏫", label: "kumain bago ang paaralan" },
    ],
    correctChoiceId: "b",
    difficulty: 1.5,
    discrimination: 1.2,
  },
  {
    id: "fil-hs-06",
    format: "hear-sentence",
    language: "fil",
    prompt: "Inilagay ng bata ang mansanas sa basket, hindi sa mesa.",
    audioUrl: "/audio/fil-hs-06.mp3",
    choices: [
      { id: "a", emoji: "🍎🔝🪑", label: "mansanas sa mesa" },
      { id: "b", emoji: "🍎⬇️🪑", label: "mansanas sa ilalim ng mesa" },
      { id: "c", emoji: "🍎➡️🧺", label: "mansanas sa basket" },
      { id: "d", emoji: "🍎➡️🎒", label: "mansanas sa bag" },
    ],
    correctChoiceId: "c",
    difficulty: 2.2,
    discrimination: 1.2,
  },

  // English — see-word
  {
    id: "en-sw-01",
    format: "see-word",
    language: "en",
    prompt: "sun",
    choices: [
      { id: "a", emoji: "🌙", label: "moon" },
      { id: "b", emoji: "☀️", label: "sun" },
      { id: "c", emoji: "⭐", label: "star" },
      { id: "d", emoji: "☁️", label: "cloud" },
    ],
    correctChoiceId: "b",
    difficulty: -2.2,
    discrimination: 1.2,
  },
  {
    id: "en-sw-02",
    format: "see-word",
    language: "en",
    prompt: "fish",
    choices: [
      { id: "a", emoji: "🐟", label: "fish" },
      { id: "b", emoji: "🦀", label: "crab" },
      { id: "c", emoji: "🐙", label: "octopus" },
      { id: "d", emoji: "🐬", label: "dolphin" },
    ],
    correctChoiceId: "a",
    difficulty: -1.2,
    discrimination: 1.2,
  },
  {
    id: "en-sw-03",
    format: "see-word",
    language: "en",
    prompt: "school",
    choices: [
      { id: "a", emoji: "🏠", label: "house" },
      { id: "b", emoji: "🏥", label: "hospital" },
      { id: "c", emoji: "🏫", label: "school" },
      { id: "d", emoji: "🏪", label: "store" },
    ],
    correctChoiceId: "c",
    difficulty: -0.4,
    discrimination: 1.2,
  },
  {
    id: "en-sw-04",
    format: "see-word",
    language: "en",
    prompt: "happy",
    choices: [
      { id: "a", emoji: "😀", label: "happy" },
      { id: "b", emoji: "😢", label: "sad" },
      { id: "c", emoji: "😴", label: "sleepy" },
      { id: "d", emoji: "🤤", label: "hungry" },
    ],
    correctChoiceId: "a",
    difficulty: 0.5,
    discrimination: 1.2,
  },
  {
    id: "en-sw-05",
    format: "see-word",
    language: "en",
    prompt: "running",
    choices: [
      { id: "a", emoji: "🛌", label: "sleeping" },
      { id: "b", emoji: "📖", label: "reading" },
      { id: "c", emoji: "🏃", label: "running" },
      { id: "d", emoji: "🍽️", label: "eating" },
    ],
    correctChoiceId: "c",
    difficulty: 1.3,
    discrimination: 1.2,
  },
  {
    id: "en-sw-06",
    format: "see-word",
    language: "en",
    prompt: "beside",
    choices: [
      { id: "a", emoji: "📖↔️✏️", label: "book beside a pencil" },
      { id: "b", emoji: "📖🔝✏️", label: "book on a pencil" },
      { id: "c", emoji: "📖⬇️✏️", label: "book under a pencil" },
      { id: "d", emoji: "📖➡️🎒", label: "book in a bag" },
    ],
    correctChoiceId: "a",
    difficulty: 2.4,
    discrimination: 1.2,
  },

  // Filipino — see-word
  {
    id: "fil-sw-01",
    format: "see-word",
    language: "fil",
    prompt: "aso",
    choices: [
      { id: "a", emoji: "🐱", label: "pusa" },
      { id: "b", emoji: "🐶", label: "aso" },
      { id: "c", emoji: "🐟", label: "isda" },
      { id: "d", emoji: "🐦", label: "ibon" },
    ],
    correctChoiceId: "b",
    difficulty: -2.2,
    discrimination: 1.2,
  },
  {
    id: "fil-sw-02",
    format: "see-word",
    language: "fil",
    prompt: "isda",
    choices: [
      { id: "a", emoji: "🦀", label: "alimango" },
      { id: "b", emoji: "🐙", label: "pugita" },
      { id: "c", emoji: "🐬", label: "dolphin" },
      { id: "d", emoji: "🐟", label: "isda" },
    ],
    correctChoiceId: "d",
    difficulty: -1.3,
    discrimination: 1.2,
  },
  {
    id: "fil-sw-03",
    format: "see-word",
    language: "fil",
    prompt: "paaralan",
    choices: [
      { id: "a", emoji: "🏥", label: "ospital" },
      { id: "b", emoji: "🏫", label: "paaralan" },
      { id: "c", emoji: "🏠", label: "bahay" },
      { id: "d", emoji: "🏪", label: "tindahan" },
    ],
    correctChoiceId: "b",
    difficulty: -0.3,
    discrimination: 1.2,
  },
  {
    id: "fil-sw-04",
    format: "see-word",
    language: "fil",
    prompt: "masaya",
    choices: [
      { id: "a", emoji: "😢", label: "malungkot" },
      { id: "b", emoji: "😴", label: "antok" },
      { id: "c", emoji: "😀", label: "masaya" },
      { id: "d", emoji: "🤤", label: "gutom" },
    ],
    correctChoiceId: "c",
    difficulty: 0.4,
    discrimination: 1.2,
  },
  {
    id: "fil-sw-05",
    format: "see-word",
    language: "fil",
    prompt: "tumatakbo",
    choices: [
      { id: "a", emoji: "🍽️", label: "kumakain" },
      { id: "b", emoji: "🏃", label: "tumatakbo" },
      { id: "c", emoji: "🛌", label: "natutulog" },
      { id: "d", emoji: "📖", label: "nagbabasa" },
    ],
    correctChoiceId: "b",
    difficulty: 1.2,
    discrimination: 1.2,
  },
  {
    id: "fil-sw-06",
    format: "see-word",
    language: "fil",
    prompt: "katabi",
    choices: [
      { id: "a", emoji: "📖🔝✏️", label: "aklat sa ibabaw ng lapis" },
      { id: "b", emoji: "📖⬇️✏️", label: "aklat sa ilalim ng lapis" },
      { id: "c", emoji: "📖↔️✏️", label: "aklat katabi ng lapis" },
      { id: "d", emoji: "📖➡️🎒", label: "aklat sa bag" },
    ],
    correctChoiceId: "c",
    difficulty: 2.5,
    discrimination: 1.2,
  },
];
