import type { Item } from "@/lib/types";

export const mockItems = [
  {
    id: "mock-en-hear-dog",
    format: "hear-word",
    language: "en",
    prompt: "dog",
    choices: [
      { id: "dog", emoji: "🐶", label: "dog" },
      { id: "cat", emoji: "🐱", label: "cat" },
      { id: "bird", emoji: "🐦", label: "bird" },
      { id: "fish", emoji: "🐟", label: "fish" },
    ],
    correctChoiceId: "dog",
    difficulty: -2.2,
    discrimination: 1.2,
  },
  {
    id: "mock-fil-hear-apple",
    format: "hear-word",
    language: "fil",
    prompt: "mansanas",
    choices: [
      { id: "apple", emoji: "🍎", label: "mansanas" },
      { id: "banana", emoji: "🍌", label: "saging" },
      { id: "grapes", emoji: "🍇", label: "ubas" },
      { id: "orange", emoji: "🍊", label: "dalandan" },
    ],
    correctChoiceId: "apple",
    difficulty: -1.8,
    discrimination: 1.2,
  },
  {
    id: "mock-en-hear-sun",
    format: "hear-sentence",
    language: "en",
    prompt: "The sun is bright.",
    choices: [
      { id: "sun", emoji: "☀️", label: "sun" },
      { id: "moon", emoji: "🌙", label: "moon" },
      { id: "cloud", emoji: "☁️", label: "cloud" },
      { id: "rain", emoji: "🌧️", label: "rain" },
    ],
    correctChoiceId: "sun",
    difficulty: -1.2,
    discrimination: 1.2,
  },
  {
    id: "mock-fil-hear-run",
    format: "hear-sentence",
    language: "fil",
    prompt: "Tumatakbo ang bata.",
    choices: [
      { id: "run", emoji: "🏃", label: "tumatakbo" },
      { id: "sleep", emoji: "😴", label: "natutulog" },
      { id: "eat", emoji: "🍽️", label: "kumakain" },
      { id: "read", emoji: "📖", label: "nagbabasa" },
    ],
    correctChoiceId: "run",
    difficulty: -0.7,
    discrimination: 1.2,
  },
  {
    id: "mock-en-see-house",
    format: "see-word",
    language: "en",
    prompt: "house",
    choices: [
      { id: "house", emoji: "🏠", label: "house" },
      { id: "school", emoji: "🏫", label: "school" },
      { id: "store", emoji: "🏪", label: "store" },
      { id: "hospital", emoji: "🏥", label: "hospital" },
    ],
    correctChoiceId: "house",
    difficulty: -0.3,
    discrimination: 1.2,
  },
  {
    id: "mock-fil-see-book",
    format: "see-word",
    language: "fil",
    prompt: "aklat",
    choices: [
      { id: "book", emoji: "📘", label: "aklat" },
      { id: "pencil", emoji: "✏️", label: "lapis" },
      { id: "bag", emoji: "🎒", label: "bag" },
      { id: "paper", emoji: "📄", label: "papel" },
    ],
    correctChoiceId: "book",
    difficulty: 0.1,
    discrimination: 1.2,
  },
  {
    id: "mock-en-hear-under",
    format: "hear-sentence",
    language: "en",
    prompt: "The cat is under the table.",
    choices: [
      { id: "under", emoji: "🐈", label: "cat under table" },
      { id: "on", emoji: "🐱", label: "cat on table" },
      { id: "beside", emoji: "🐈‍⬛", label: "cat beside table" },
      { id: "far", emoji: "🐾", label: "cat far away" },
    ],
    correctChoiceId: "under",
    difficulty: 0.6,
    discrimination: 1.2,
  },
  {
    id: "mock-fil-hear-help",
    format: "hear-sentence",
    language: "fil",
    prompt: "Tinulungan ni Ana ang kanyang kaibigan.",
    choices: [
      { id: "help", emoji: "🤝", label: "tumulong" },
      { id: "wave", emoji: "👋", label: "kumaway" },
      { id: "hide", emoji: "🙈", label: "nagtago" },
      { id: "cry", emoji: "😢", label: "umiyak" },
    ],
    correctChoiceId: "help",
    difficulty: 1.1,
    discrimination: 1.2,
  },
  {
    id: "mock-en-see-gentle",
    format: "see-word",
    language: "en",
    prompt: "gentle",
    choices: [
      { id: "gentle", emoji: "🫶", label: "gentle" },
      { id: "angry", emoji: "😠", label: "angry" },
      { id: "loud", emoji: "📣", label: "loud" },
      { id: "fast", emoji: "💨", label: "fast" },
    ],
    correctChoiceId: "gentle",
    difficulty: 1.7,
    discrimination: 1.2,
  },
  {
    id: "mock-fil-see-careful",
    format: "see-word",
    language: "fil",
    prompt: "maingat",
    choices: [
      { id: "careful", emoji: "🧘", label: "maingat" },
      { id: "hurried", emoji: "🏃‍➡️", label: "nagmamadali" },
      { id: "sleepy", emoji: "🥱", label: "inaantok" },
      { id: "noisy", emoji: "🥁", label: "maingay" },
    ],
    correctChoiceId: "careful",
    difficulty: 2.2,
    discrimination: 1.2,
  },
] satisfies Item[];
